name: Node.js CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Lint Check (syntax errors)
        run: |
          npm install eslint
          npx eslint app.js views/index.html || exit 1

      # OPTIONAL: Add test script
      # - name: Run Tests
      #   run: npm test

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Basic Test (Mock)
        run: echo "✅ Tests passed!"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Webhook
        run: |
          curl -X GET https://api.render.com/deploy/srv-d0skfbidbo4c73f5ps20?key=N9-Wf-POgEU
